### ISSUE TITLE
Suggestion: check for a "numeric" string

### ISSUE THREAD

**Issue by ComFreek** [kislyuk/ensure#12]
I've got a program which receives commands through some transport layers as strings (e.g. "!do sleep 3"). It seems that `ensure()` is the perfect fit for my command classes to verify the passed number of arguments and data types. However, the arguments are provided as strings, so I cannot check for correctness by `ensure(123).is_an(int)`.

Useful test cases:

```
ensure("123").is_a_numeric_string()
ensure("+123").is_a_numeric_string()
ensure("-123").is_a_numeric_string()
ensure("1.5").is_a_numeric_string()
ensure("-1.5").is_a_numeric_string()

ensure("123abc")  # Raises an exception!
ensure("abc123")  # Raises an exception!
```

Possible implementation: 

```
def is_numeric_string(str):
    try:
        int(str)
        return True
    except ValueError:
        return False
```

PS: Is this library still actively developed and updated on PyPi? I see that the latest version on PyPi is from July last year. The last commit date of this repository definitely indicates the opposite.

**Comment by kislyuk** [comment]
Good suggestion. I'll go ahead and add that.

**Comment by ComFreek** [comment]
Thanks! :smile:
