### ISSUE TITLE
Custom predicates?

### ISSUE THREAD

**Issue by dpercy** [kislyuk/ensure#14]
Suppose I want to convert this assertion to ensure:
```
from path import path
link = path('spam/and/eggs')
assert link.isabs()  # raises AssertionError
```

I can use `with_args` or `called_with`, but then the subject of the assertion isn't `link`:
```
ensure(path.isabs).called_with(link).is_true()
# ensure.EnsureError: False is not true
```

Is there currently a way to pass in an arbitrary callable as a predicate?  Something like
```
ensure(link).satisfies(path.isabs)
# ensure.EnsureError: path('spam/and/eggs') does not satisfy <unbound method path.isabs>
```

**Comment by kislyuk** [comment]
This sounds like a great idea. I understand the extra semantic value of having the assertion refer more specifically to the predicate. Do you want to try sketching out an implementation in a pull request?

**Comment by dpercy** [comment]
Sure thing; here it is: https://github.com/kislyuk/ensure/pull/16
