### ISSUE TITLE
Return boolean values?

### ISSUE THREAD

**Issue by eshansingh** [kislyuk/ensure#22]
Hey, I've been using ensure as contracts for functions, but it's pretty tricky due to the varying nature of return values. Can we have an option in the `Ensure` constructor to return a simple boolean True/False value? Or, and I think this is a much better solution because it allows for chaining, simply implement `__bool__` for all values returned by predicates to return the actual pass/fail status.

**Comment by kislyuk** [comment]
Implementing __bool__ seems like a good idea. I won't have time for this until next week at the earliest. Would you like to take a stab at it?

**Comment by eshansingh** [comment]
@kislyuk I'm at work right now, but I'll give it a try when I get back.

**Comment by eshansingh** [comment]
@kislyuk See #23. This is a pretty simple change.
