### ISSUE TITLE
has_key() triggers linters

### ISSUE THREAD

**Issue by eykd** [kislyuk/ensure#25]
`has_key` triggers linters which are guarding against the usage of `dict.has_key()`, a deprecated interface.

Would it be possible to get a synonym for `has_key()` which also returns a `KeyInspector`? If all I care about is the present of the key, I can use `contains()`, but that returns a `ChainInspector`, and sometimes I'd like to check the value of the key too without the linter yelling at me. :)

**Comment by kislyuk** [comment]
Sorry I missed this.

I added `contains_key`, an alias for `has_key`. Does this work for you?

**Comment by eykd** [comment]
That's perfect, thanks.
