### ISSUE TITLE
Support an is_sorted condition

### ISSUE THREAD

**Issue by lakshayg** [kislyuk/ensure#26]
It would be great if it was possible to do something like:

```python
ensure([1, 2, 3]).is_sorted()
ensure([3, 2, 1]).is_sorted(key=lambda x: -x)
```

**Comment by kislyuk** [comment]
Released in v0.7.0, please test.

**Comment by lakshayg** [comment]
Cool. Thanks a lot.

**Comment by lakshayg** [comment]
I just saw your implementation and I have a concern, you compute the sorted version and then assert for equality, right? An alternative would be to do something like:

```python
for i in range(len(iterable)):
    assertGreaterOrEqual(key(iterable[i+1]), key(iterable[i]))
```

What do you say?
