### ISSUE TITLE
Adjust to upcoming Python 3.8 / fix deprecation warning

### ISSUE THREAD

**Issue by ccwienk** [kislyuk/ensure#27]
When using ensure in unittests run with pytest with Python3.7, the following warning is emitted:

```
site-packages/ensure/__init__.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

So I suppose this should not be hard to fix, but it would be a good idea to do so.

**Comment by kislyuk** [comment]
Released in v0.8.1, thanks.
